apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1 
kind: Service 
metadata:
  name: nodejs 
  labels:
    app: nodejs
spec: 
  selector:
    app: nodejs
  ports:
    - name: service-port
      port: 5152
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: nodejs 
  labels:
    app: nodejs
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: deployment-port
          image: nombre-imagen
          imagePullPolicy: "Never"
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits: 
              cpu: "100m"
              memory: "128Mi"
          env:
            - name: VAR_TEST
              value: "valorTest"